--- #YAML:1.0
name:               Snapback2
version:            0.914
abstract:           Snapback2 -- automated rsync backup
author:
    - Mike Heins <snapback2@perusion.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Config::ApacheFormat:  1.2
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.54
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
